libsite/libsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from lipapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^lipapp/', include('lipapp.urls', namespace='lipapp')),
]

libsite/lipapp/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [

        # url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        # url(r'^(?P<item_id>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
        url(r'^(?P<item_id>\d+)/$', views.detail, name='detail'),
        url(r'^suggestions/$', views.suggestions, name='suggestions'),
        url(r'^newitem/$', views.newitem, name='newitem'),
        url(r'^searchlib/$', views.searchlib, name='searchlib'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^myitems/$', views.myitems, name='myitems'),
        url(r'^register/$', views.register, name='register'),
        url(r'^suggestions/(?P<item_id>\d+)/$', views.suggestiondetail, name='suggestiondetail')

]

libsite/lipapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


def clean_fields(value):
    if value < 1900 or value > 2016:
        raise ValidationError('pubyr must be between 1900 and 2016')


class Libuser(User):
    PROVINCE_CHOICES = (
        ('AB', 'Alberta'),  # The first value is actually stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    phone = models.IntegerField(null=True)
    postalcode = models.CharField(max_length=7, null=True, blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Libitem(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD', 'DVD'),
        ('Other', 'Other'),
    )

    title = models.CharField(max_length=100)
    itemtype = models.CharField(max_length=6, choices=TYPE_CHOICES, default='Book')
    checked_out = models.BooleanField(default=False)
    user = models.ForeignKey(Libuser, default=None, null=True, blank=True)
    duedate = models.DateField(default=None, null=True, blank=True)
    last_chkout = models.DateField(default=None, null=True, blank=True)
    date_acquired = models.DateField(default=datetime.date.today())
    pubyr = models.IntegerField(validators=[clean_fields])
    # pubyr = models.IntegerField()
    num_chkout = models.IntegerField(default=0)

    def __str__(self):
        return self.title + ', ItemType:' + self.itemtype

    def overdue(self):
        if self.checked_out == True:
             if self.duedate < datetime.date.today():
                return 'Yes'
             else:
                 return 'No'


class Book(Libitem):
    CATEGORY_CHOICES = (
        (1, 'Fiction'),
        (2, 'Biography'),
        (3, 'Self Help'),
        (4, 'Education'),
        (5, 'Children'),
        (6, 'Teen'),
        (7, 'Other'),
    )
    author = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)

    def __str__(self):
        return self.title + ' by ' + self.author


class Dvd(Libitem):
    maker = models.CharField(max_length=100)
    duration = models.IntegerField()

    RATING_CHOICES = (
        ('G', 'G'),
        ('PG', 'PG'),
        ('PG-13', 'PG-13'),
        ('14A', '14A'),
        ('R', 'R'),
        ('NR', 'NR'),
    )

    rating = models.CharField(max_length=10, choices=RATING_CHOICES, blank=True)

    def __str__(self):
        return ' '+self.title + ' by ' + self.maker


class Suggestion(models.Model):

    TYPE_CHOICES = (
        (1, 'Book'),
        (2, 'DVD'),
        (3, 'Other'),
    )
    title = models.CharField(max_length=100, default='')
    pubyr = models.IntegerField(null=True, blank=True)
    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    cost = models.IntegerField()
    num_interested = models.IntegerField()
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title + ', People Interested: ' + str(self.num_interested)

libsite/lipapp/forms.py
from django import forms
from django.contrib.auth.models import User
from lipapp.models import Suggestion


class SuggestionForm(forms.ModelForm):
    TYPE_CHOICES = (
        (1, 'Book'),
        (2, 'DVD'),
        (3, 'Other'),
    )

    type = forms.IntegerField(widget=forms.RadioSelect(choices=TYPE_CHOICES))
    title = forms.CharField(max_length=100, required=True)
    cost = forms.IntegerField(label='Estimated Cost In Dollars')

    class Meta:
        model = Suggestion
        fields = ['title', 'type', 'pubyr', 'cost', 'comments']
        # widgets={
        # 'type' = forms.RadioSelect
        # }


class SearchlibForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    author = forms.CharField(max_length=100, required=False)


class LoginForm(forms.ModelForm):

    password = forms.CharField(required=True, widget=forms.PasswordInput)
    username = forms.CharField(error_messages={'required': 'This field is required'})

    class Meta:
        model = User
        fields = ['username', 'password']


class RegisterForm(forms.ModelForm):
    username = forms.CharField(error_messages={'required': 'This field is required'})
    password2 = forms.CharField(required=True,label="Repeat Password", widget=forms.PasswordInput)
    email = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        widgets = {'email': forms.EmailInput,
                   'password': forms.PasswordInput}

libsite/lipapp/views.py
# import necessary classes
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from lipapp.models import Book, Dvd, Libuser, Libitem, Suggestion
from .forms import SuggestionForm, SearchlibForm, LoginForm, RegisterForm
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from datetime import datetime
from random import randint
from django.views import generic


# @login_required
# class IndexView(generic.ListView):
#     template_name = 'lipapp/index.html'
#     context_object_name = 'itemlist'
#
#     def get_queryset(self, request):
#         value = 0
#         if 'luckynum' in request.session:
#             value = request.session['luckynum']
#         itemlist = Libitem.objects.all().order_by('title')[:10]
#         return render(request, 'lipapp/index.html', {'itemlist': itemlist, 'user': request.user, 'value': value})


@login_required
def index(request):
    value = 0
    if 'luckynum' in request.session:
        value = request.session['luckynum']
    itemlist = Libitem.objects.all().order_by('title')[:10]
    return render(request, 'lipapp/index.html', {'itemlist': itemlist, 'user': request.user, 'value': value})


def about(request):
    visits = int(request.COOKIES.get('visits', '0'))
    response = render(request, 'lipapp/about.html', {'user': request.user, 'visits': visits})

    # Does the cookie last_visit exist?
    if 'about_visits' in request.COOKIES:
        # Get the cookie's value.
        about_visits = request.COOKIES['about_visits']
        # Cast the value to a Python date/time object.
        about_visits_time = datetime.strptime(about_visits[:-7], "%Y-%m-%d %H:%M:%S")

        # Set time to 5 minutes = 300 seconds
        if (datetime.now() - about_visits_time).seconds > 300:
            # ...reassign the value of the cookie to +1 of what it was before...
            response.set_cookie('visits', visits + 1)
            # ...and update the last visit cookie, too.
            response.set_cookie('about_visits', datetime.now())
    else:
        # Cookie last_visit doesn't exist, so create it to the current date/time.
        response.set_cookie('about_visits', datetime.now())

    # Return response back to the user, updating any cookies that need changed.
    return response


@login_required
def detail(request, item_id):
    libitem = get_object_or_404(Libitem, pk=item_id)
    itemtype = libitem.__getattribute__('itemtype')

    if itemtype == 'Book':
        author = Book.objects.get(pk=item_id).__getattribute__('author')
        category = Book.objects.get(pk=item_id).__getattribute__('category')
        context = {'libitem': libitem, 'author': author, 'category': category, 'user': request.user}
        return render(request, 'lipapp/detail.html', context)

    elif itemtype == 'DVD':
        maker = Dvd.objects.get(pk=item_id).__getattribute__('maker')
        duration = Dvd.objects.get(pk=item_id).__getattribute__('duration')
        rating = Dvd.objects.get(pk=item_id).__getattribute__('rating')
        context = {'libitem': libitem, 'maker': maker, 'duration': duration, 'rating': rating, 'user': request.user}
        return render(request, 'lipapp/detail.html', context)


@login_required
def suggestions(request):
    suggestionlist = Suggestion.objects.all()[:10]
    return render(request, 'lipapp/suggestions.html', {'itemlist': suggestionlist, 'user': request.user})


def suggestiondetail(request, item_id):
    suggestion = get_object_or_404(Suggestion, pk=item_id)
    return render(request, 'lipapp/suggestiondetail.html', {'suggestion': suggestion})



@login_required
def newitem(request):
    suggestions = Suggestion.objects.all()
    if request.method == 'POST':
        form = SuggestionForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.num_interested = 1
            suggestion.save()
            return HttpResponseRedirect(reverse('lipapp:suggestions'))
        else:
            return render(request, 'lipapp/newitem.html', {'form':form, 'suggestions':suggestions})
    else:
        form = SuggestionForm()
        return render(request, 'lipapp/newitem.html', {'form':form, 'suggestions':suggestions})


@login_required
def searchlib(request):
    results = []
    if request.method == 'GET':
        form = SearchlibForm()

    else:
        form = SearchlibForm(request.POST)
        if form.is_valid():
            title_query = form.cleaned_data['title']
            author_query = form.cleaned_data['author']

            if title_query != '' and author_query != '':
                results = Book.objects.filter(title__icontains=title_query, author__icontains=author_query)
                if not results:
                    return render(request, 'lipapp/searchlib.html',
                                  {'form': form, 'message': "No Match Found", 'user': request.user})

            elif title_query != '':
                results = Libitem.objects.filter(title__icontains=title_query)
                if not results:
                    return render(request, 'lipapp/searchlib.html',
                                  {'form': form, 'message': "No Match Found", 'user': request.user})

            elif author_query != '':
                results = Book.objects.filter(author__icontains=author_query)
                if not results:
                    return render(request, 'lipapp/searchlib.html',
                                  {'form': form, 'message': "No Match Found", 'user': request.user})

            else:  # title_query == '' and author_query == ''
                return render(request, 'lipapp/searchlib.html',
                              {'form': form, 'message': "Please submit a search term"})

    return render(request, 'lipapp/searchlib.html', {'form': form, 'results': results, 'user': request.user})


def user_login(request):
    random_number = randint(1, 9)
    request.session['luckynum'] = random_number
    request.session.set_expiry(3600)

    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('lipapp:index'))
            else:
                return render(request, 'lipapp/login.html', {'error_message': 'Your account has been disabled'})

        elif not user and (username != '' and password != ''):
            return render(request, 'lipapp/login.html', {'form': form, 'error_message': 'Invalid login details.'})

        else:
            return render(request, 'lipapp/login.html', {'form': form})
        # return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    else:
        form = LoginForm()
        return render(request, 'lipapp/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('lipapp:index'))


@login_required
def myitems(request):
    user = Libuser.objects.get(username=request.user.username)
    if user:
        itemlist = Libitem.objects.filter(checked_out=True, user=user)
        return render(request, 'lipapp/myitems.html', {'itemlist': itemlist, 'user': request.user})
    else:
        return HttpResponse('You are not a Libuser')


def register(request):
    return render(request, 'lipapp/register.html')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = None
            try:
                user = Libuser.objects.get(username=form.cleaned_data['username'])
            except Exception as e:
                print(e)
            if user is not None:
                message = "User name is currently in use"
                return render(request, 'lipapp/register.html', {'form': form, 'error_message': message})

            try:
                user = Libuser.objects.get(email=form.cleaned_data['email'])
            except Exception as e:
                print(e)
            if user is not None:
                message = "Email already registered"
                return render(request, 'lipapp/register.html', {'form': form, 'error_message': message})

            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            if password2 != password:
                message = "Passwords don't match"
                return render(request, 'lipapp/register.html', {'form': form, 'error_message': message})

            user = Libuser.objects.create_user(
                username=form.cleaned_data['username'],
                first_name=form.cleaned_data['first_name'],
                email=form.cleaned_data['email'],
                last_name=form.cleaned_data['last_name'],
                password=form.cleaned_data['password'],
            )
            user.save()
            message = "Registration Successful! "
            form = RegisterForm()
            return render(request, 'lipapp/register.html', {'form': form, 'success_message': message})
        else:
            return render(request, 'lipapp/register.html', {'form': form})
    else:
        form = RegisterForm()
        return render(request, 'lipapp/register.html', {'form': form})

libsite/lipapp/templates/lipapp/about_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<h3>This is the about page</h3>

<p><a href="{% url 'lipapp:index' %}">Return to Home Page</a></p>
<p><a href="/lipapp">Return to Home Page</a></p>

</body>
</html>>

libsite/lipapp/templates/lipapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

      <!-- Bootstrap -->
        <link href="{% static 'lipapp/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'lipapp/style.css' %}" />
        <title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->

        <script src="{% static 'lipapp/js/main.js' %}"></script>
        <script src="{% static 'lipapp/js/bootstrap.min.js' %}"></script>

    <style>
        body {
            background: white url({% static 'lipapp/images/books-pile.jpg'%}) center fixed;
            background-size: cover;
        }

        ul{
            list-style-type: none;
        }

    </style>


  </head>
  <body>
      <nav role="navigation" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">

            <div class="navbar-header">
                <a href="{% url 'lipapp:index' %}" class="navbar-brand" style="width: 170px; font-style: inherit;">
                    <strong>MAC &nbsp;LIBRARY</strong></a>
                <button type="button" class="navbar-toggle" data-target="#navbarCollapse" data-toggle="collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbarCollapse">
                    <ul class="nav navbar-nav">
                        <li class="{% block index_active %}{% endblock %}"><a href="{% url 'lipapp:index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>
                        <li class="{% block suggest_active %}{% endblock %}"><a href="{% url 'lipapp:suggestions' %}"><span class="glyphicon glyphicon-list"></span>&nbsp;Suggestions</a></li>
                        <li class="{% block newitem_active %}{% endblock %}"><a href="{% url 'lipapp:newitem' %}"><span class="glyphicon glyphicon-plus"></span>&nbsp;Suggest Item</a></li>
                        <li class="{% block search_active %}{% endblock %}"><a href="{% url 'lipapp:searchlib' %}"><span class="glyphicon glyphicon-search"></span>&nbsp;Search</a></li>
                        <li class="{% block myitem_active %}{% endblock %}"><a href="{% url 'lipapp:myitems' %}"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;My Items</a></li>
                        <li class="{% block about_active %}{% endblock %}"><a href="{% url 'lipapp:about' %}"><span>@</span>&nbsp;About site</a></li>
                    </ul>

                      <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a href=""><span class="glyphicon glyphicon-user"></span>&nbsp;Hello&nbsp;{{ user.first_name }}</a></li>
                            <li ><a href="{% url 'lipapp:logout' %}"><span class="glyphicon glyphicon-off"></span>&nbsp;LogOut</a></li>

                        {% else %}
                            <li ><a href="{% url 'lipapp:index' %}"><span class="glyphicon glyphicon-off"></span>&nbsp;LogIn</a></li>
                        {% endif %}
                      </ul>

            </div>


        </div>
      </nav>

            <div class="container-fluid" style="margin-top:60px">
                <h1>{% block myhdg %}{% endblock %}</h1>

                {% block body_block %}{% endblock %}

            </div>


    <div class="footer" style="margin-top: 450px">
          <div class="container">
              <p>&copy; Developed with <strong style="font-size: 20px;">&hearts;</strong></p>
          </div>
    </div>

  </body>
</html>

{#<!DOCTYPE html>#}
{#{% load staticfiles %}#}
{##}
{#<html>#}
{#    <head>#}
{#        <meta charset="utf-8">#}
{#        <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#        <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->#}
{#    <!-- Bootstrap -->#}
{#        <link href="{% static 'lipapp/css/bootstrap.min.css' %}" rel="stylesheet">#}
{#        <link rel="stylesheet" type="text/css" href="{% static 'lipapp/style.css' %}" />#}
{#        <title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>#}
{##}
{#    <style>#}
{#        body {#}
{#            background: white url({% static 'lipapp/images/books-pile.jpg'%}) center fixed;#}
{#            background-size: cover;#}
{#        }#}
{#    </style>#}
{##}
{#    </head>#}
{##}
{#    <body>#}
{##}
{#        <nav role="navigation" class="navbar navbar-inverse navbar-fixed-top">#}
{#            <div class="container-fluid">#}
{##}
{#                <div class="navbar-header">#}
{#                    <a href="#" class="navbar-brand">MAC Library</a>#}
{#                    <button type="button" class="navbar-toggle" data-target="#navbarCollapse" data-toggle="collapse">#}
{#                        <span class="sr-only">Toggle Navigation</span>#}
{#                         <span class="icon-bar"></span>#}
{#                        <span class="icon-bar"></span>#}
{#                        <span class="icon-bar"></span>#}
{#                    </button>#}
{#                </div>#}
{##}
{##}
{#                <div class="navbar-collapse collapse" id="navbarCollapse">#}
{#                    <ul class="nav navbar-nav">#}
{#                        <li class="active"><a href="{% url 'lipapp:index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>#}
{#                        <li><a href="{% url 'lipapp:suggestions' %}"><span class="glyphicon glyphicon-list"></span>&nbsp;Suggestions</a></li>#}
{#                        <li><a href="{% url 'lipapp:newitem' %}"><span class="glyphicon glyphicon-plus"></span>&nbsp;Suggest Item</a></li>#}
{#                        <li><a href="{% url 'lipapp:searchlib' %}"><span class="glyphicon glyphicon-search"></span>&nbsp;Search</a></li>#}
{#                        <li><a href="{% url 'lipapp:about' %}"><span>@</span>&nbsp;About site</a></li>#}
{#                    </ul>#}
{##}
{##}
{#                    <ul class="nav navbar-nav navbar-right">#}
{#                    {% if user.is_authenticated %}#}
{#                        <li><span class="glyphicon glyphicon-user"></span>&nbsp;Hello{{ user.first_name }}</li>#}
{#                        <li ><a href="#">LogOut<span class="glyphicon glyphicon-off"></span></a></li>#}
{#                    </ul>#}
{#                    {% else %}#}
{#                        <li ><a href="#">LogIn<span class="glyphicon glyphicon-off"></span></a></li>#}
{#                    {% endif %}#}
{#                </div>#}
{##}
{#            </div>#}
{#        </nav>#}
{##}
{#    <div class="container-fluid" style="margin-top:60px">#}
{#        <h1>{% block myhdg %}{% endblock %}</h1>#}
{#        {% block body_block %}{% endblock %}#}
{#    </div>#}
{##}
{##}
{#    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>#}
{#    <!-- Include all compiled plugins (below), or include individual files as needed -->#}
{#    <script src="js/bootstrap.min.js"></script>#}
{#    </body>#}
{#</html>#}
{##}

libsite/lipapp/templates/lipapp/index_old.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
</head>

<body>


                <div class="list-group col-xs-10 col-md-6">
                <h2>List of Library Items</h2>
                    {% for item in itemlist %}
                        {%if item.itemtype == 'Book' %}

                    <a href="{% url 'lipapp:detail' item.id %}" class="list-group-item"><b>{{ item.title }}</b>
                    <span class="badge">Book</span></a>


                        {% elif item.itemtype == 'DVD'%}

                    <a href="{% url 'lipapp:detail' item.id %}" class="list-group-item"><b>{{ item.title }}</b>
                        <span class="badge">DVD</span></a>


                        {% endif %}

                    {% endfor %}
                </div>




{#        <ol>#}
{#                <div class="list-group col-xs-10 col-md-6">#}
{#                <h2>List of Library Items</h2>#}
{#                    {% for item in itemlist %}#}
{#                        {%if item.itemtype == 'Book' %}#}
{#                    <ul>#}
{#                    <li><a href="{% url 'lipapp:detail' item.id %}" class="list-group-item"><b>{{ item.title }}</b>#}
                    {#<span class="glyphicon glyphicon-book"></span></a></li>#}
{##}
{#                    </ul>#}
{#                        {% elif item.itemtype == 'DVD'%}#}
{#                    <ul>#}
{#                    <li><a href="{% url 'lipapp:detail' item.id %}" class="list-group-item"><b>{{ item.title }}</b>#}
                        {#<span class="glyphicon glyphicon-record"></span></a></li>#}
{##}
{#                    </ul>#}
{#                        {% endif %}#}
{##}
{#                    {% endfor %}#}
{#                </div>#}
{#        </ol>#}

</body>
</html>

libsite/lipapp/templates/lipapp/login.html
{% extends 'lipapp/base.html' %}
{% block title %}Login{% endblock %}



    {% block body_block %}
      <div class="container-fluid "  style="margin-top:60px">

          <div class="row" style=" ">
              <div class="col-sm-12 col-md-4">
                  <div class="panel panel-default loginPanel">
                      <div class="panel-body">

                    <h3 style="margin-bottom:30px; ">Log In</h3>
                      {% if error_message %}
                      <div id="alert1" class="alert alert-danger">
                        <a class="close" data-dismiss="alert">&times;
                        </a><strong>{{ error_message }}</strong>
                     </div>
                      {% endif %}

                        <form action="/accounts/login/" role="form" method="post" class="form-horizontal">
                            {% csrf_token %}
                            {% include 'lipapp/form-template.html' %}

                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-10">
                                    <button type="submit" class="btn btn-info">Login</button>
                                </div>
                            </div>
{#                             <p align="right"><input type="submit" value="Login"></p>#}
                        </form>
{#    </div>#}

{#        <p><a href="{% url 'lipapp:register' %}">Not Register?</a></p>#}

                      </div>

                      <div class="panel-footer">
                            Don't have an account? <a href="{% url 'lipapp:register' %}">Click here</a> to register.
                      </div>

                  </div>
              </div>
          </div>

      </div>
      {% endblock %}

libsite/lipapp/templates/lipapp/suggestions.html
{% extends 'lipapp/base.html' %}
{% block title %}Suggestion{% endblock %}
{% block suggest_active %}active{% endblock %}
{% block myhdg %}Suggestions{% endblock %}

{% block body_block %}

     <div class="list-group col-xs-10 col-md-6">
    {% if itemlist %}
        <ul>
            {% for item in itemlist %}

                {%if item.type == 1 %}
                <ul>
                 <li class="list-group-item">
                     <a href="{% url 'lipapp:suggestiondetail' item.id %}" class="list-group-item"><b>{{ item.title }}
                     </b><span class="badge">Book</span></a></li>
                </ul>

                {%elif item.type == 2 %}
                 <ul>
                 <li class="list-group-item">
                     <a href="{% url 'lipapp:suggestiondetail' item.id %}" class="list-group-item"><b>{{ item.title }}
                     </b><span class="badge">DVD</span></a></li>
                </ul>

                 {%elif item.type == 3 %}
                 <ul>
                 <li class="list-group-item">
                     <a href="{% url 'lipapp:suggestiondetail' item.id %}" class="list-group-item"><b>{{ item.title }}
                     </b><span class="badge">Other</span></a></li>
                </ul>

                {% endif %}

            {% endfor %}
        </ul>

         <div class="col-sm-offset-6 col-sm-10">
            <a href="{% url 'lipapp:newitem' %}" class="btn btn-info" role="button">New Item</a>
         </div>
    </div>

    {% else %}
        <div id="alert2" class="alert alert-warning">
            <a class="close" data-dismiss="alert">&times;
            </a> <strong>There are no suggested  items!</strong>
        </div>

    {% endif %}
{% endblock %}

{% block suggestion %}{% endblock %}


<div class="list-group col-xs-10 col-md-6">
                <h2>List of Library Items</h2>
                    {% for item in itemlist %}
                    <ul type="none">
                    <li><a href="{% url 'lipapp:detail' item.id %}" class="list-group-item">{{ item.title }}</a></li>
{#                     <li> {{ item.itemtype }}:  {{ item}} </li>#}
                    </ul>
                    {% endfor %}
                </div>